spring.application.name=OrderingProject

spring.datasource.url=jdbc:mysql://localhost:3306/orderingProject?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=Razak!@#123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

razorpay.api.key=rzp_test_TKO6Ctz5vDRU9D
razorpay.api.secret=pj607rjDvVoC1jEn2GRryCUf
app.cors.allowed-origin-patterns=http://localhost:63342

jwt.secret=MyVeryStrongJwtSecretKeyForFreshCart2026#
jwt.expiration=3600000